### ISSUE TITLE
As a visitor, I want to learn what the web application is about before signing up.

### ISSUE THREAD

**Issue by bencrbcp** [mazohu/fortune-cookie#6]
(Front-end)
- [x] This would involve making a stylized "about" page.
- [x] The about page would be included as a tab in the landing page menu.

**Comment by delicious-echidna** [comment]
the about page would be included in the landing page menu.

**Comment by delicious-echidna** [comment]
The about page is now apart of the landing page. Design-wise it makes more sense for the user to learn more by scrolling down. We can still add a menu option to have the user be hyperlinked to that particular section if possible.

**Comment by delicious-echidna** [comment]
All tasks were completed.
